---
#
# This playbook assumes the WebSphere MQ file provided by IBM has already been
# downloaded to a specific directory (target.wd) on the server. 
#
# ${target.wd} is a variable representing the working directory on the target
# server the MQ client will be installed.
#
# Note: Although this playbook is designed to be able to be run independently,
# it is in fact part of a longer playbook and therefore may have some other
# unexpected dependencies not reflected here.
#

#
# WebSphere MQ Settings
#
#
# Install WebSphere MQ 
#
-
  name: WebSphere MQ 7.5 role
  user: root

- include: websphere-mq-install.yml

- include: websphere-mq-update.yml

