---
#
# This playbook assumes the WebSphere MQ file provided by IBM has already been
# downloaded to a specific directory (target.wd) on the server. 
#
# ${target.wd} is a variable representing the working directory on the target
# server the MQ client will be installed.
#
# Note: Although this playbook is designed to be able to be run independently,
# it is in fact part of a longer playbook and therefore may have some other
# unexpected dependencies not reflected here.
#

#
# WebSphere MQ Settings
#
#
# Install WebSphere MQ 
#

- name: Create install directory
  file: path={{ websphere_mq_update.wd }} state=directory

- name: Untar MQ Client
  command: tar zxf /vagrant/{{ websphere_mq_update.zip_file }}
    chdir={{ websphere_mq_update.wd }}
    creates={{ websphere_mq_update.wd }}/MQSeriesRuntime{{ websphere_mq_update.rpm_suffix }}
      
- name: Install MQ series packages using yum
  yum: name={{ item }} state=present
  with_items:
    - '{{ websphere_mq_update.wd }}/MQSeriesRuntime{{ websphere_mq_update.rpm_suffix }}'
    - '{{ websphere_mq_update.wd }}/MQSeriesServer{{ websphere_mq_update.rpm_suffix }}'
    - '{{ websphere_mq_update.wd }}/MQSeriesJRE{{ websphere_mq_update.rpm_suffix }}'
    - '{{ websphere_mq_update.wd }}/MQSeriesJava{{ websphere_mq_update.rpm_suffix }}'

- name: Checking primary MQ installation
  action: shell grep -E 'FilePath=/opt/mqm$' /etc/opt/mqm/mqinst.ini | wc -l
  register: is_primary_mq_set

- name: Setup primary MQ installation
  command: '{{ websphere_mq_update.prefix }}/bin/setmqinst -i -p {{ websphere_mq_update.prefix }}'
  when: '{{ is_primary_mq_set.stdout }} == 0'

