---
im:
  user:
    name: mqm
    home: /var/mqm
  packages:
    - libselinux-python
  version: 1.8.3000.20150606_0047
  prefix: /opt/IBM/IM
  wd: /vagrant/im18/1.8.3
  kernel_params:
    - { name: kernel.shmmni, value: 4096 }
    - { name: kernel.shmall, value: 2097152 }
    - { name: kernel.shmmax, value: 268435456 }
    - { name: kernel.sem, value: '"500 256000 250 1024"' }
    - { name: fs.file-max, value: 524288 }
    - { name: net.ipv4.tcp_keepalive_time, value: 180 }
  limits:
    - { name: mqm.*soft.*nofile, value: mqm soft nofile 10240 }
    - { name: mqm.*hard.*nofile, value: mqm hard nofile 10240 }
    - { name: mqm.*soft.*nproc, value: mqm soft nproc 4096 }
    - { name: mqm.*hard.*nproc, value: mqm hard nproc 4096 }

im_update:
  zip_file: 7.5.0-WS-MQ-LinuxX64-FP0004.tar.gz
  rpm_suffix: '-U8003-8.0.0-3.x86_64.rpm'
  prefix: /opt/mqm
  wd: /vagrant/mq80/8.0.0-3

